export const experiencia = [
  {
    titulo: "Desarrollador Front-End React",
    empresa: "Bee",
    institucion: "CoderHouse",
    tipoContrato: "Contrato temporal",
    periodo: "octubre 2023",
    ubicacion: "Provincia de Buenos Aires, Argentina (Remoto)",
    descripcion: "Durante mi trabajo como Desarrollador Front-End React, me encargué de implementar interfaces de usuario basadas en los diseños proporcionados por el equipo de diseño, asegurando una experiencia fluida y consistente. Desarrollé componentes reutilizables y modulares para mejorar la escalabilidad y mantenibilidad del código. Optimizé el rendimiento de la aplicación aplicando buenas prácticas en React.js, gestionando eficientemente el estado y optimizando el enrutamiento. Además, trabajé en estrecha colaboración con diseñadores y otros desarrolladores para garantizar la coherencia y calidad del producto final. También participé en revisiones de código, pruebas y refactorización para mejorar la eficiencia y la calidad del desarrollo.",
    responsabilidades: [
      "Implementar interfaces de usuario basadas en los diseños proporcionados por el equipo de diseño, asegurando una experiencia de usuario fluida y consistente.",
      "Desarrollar componentes reutilizables y modulares para mejorar la escalabilidad y mantenibilidad del código.",
      "Optimizar el rendimiento de la aplicación mediante buenas prácticas en React.js, incluyendo la gestión eficiente del estado y la optimización del enrutamiento.",
      "Colaborar con diseñadores y otros desarrolladores para garantizar la coherencia y calidad del producto final.",
      "Participar en revisiones de código, pruebas y refactorización para mejorar la calidad y eficiencia del desarrollo.",
    ],
  },
  {
    titulo: "Jefe de Proyecto | Desarrollador Full-Stack",
    empresa: "Start-Up TI Simulada",
    institucion: "Escuela Técnica N°29 D.E.06 'Reconquista de Buenos Aires'",
    tipoContrato: "Contrato de formación",
    periodo: "enero 2022",
    ubicacion: "Argentina (Híbrido)",
    descripcion: "Como Jefe de Proyecto y Desarrollador Full-Stack, supervisé y coordiné el desarrollo de dos proyectos tecnológicos, asegurando el cumplimiento de los objetivos y plazos. Gestioné y mantuve la documentación técnica para facilitar la comunicación entre los equipos. Lideré y guié al equipo de desarrollo, promoviendo buenas prácticas y metodologías ágiles como Scrum para mejorar la eficiencia del flujo de trabajo. Desarrollé y mantuve funcionalidades tanto en el backend como en el frontend utilizando PHP, Composer y PHPMyAdmin. También administré bases de datos MySQL, optimizando consultas y garantizando la integridad de los datos. Además, participé en la creación de soluciones en HTML, CSS y JavaScript, asegurando una mejor experiencia de usuario. Para garantizar la estabilidad del sistema, desarrollé unidades de prueba y realicé depuración de código. Por último, colaboré en la estrategia de ventas y marketing técnico, simulando escenarios de negocio reales.",
    responsabilidades: [
      "Supervisar y coordinar el desarrollo de dos proyectos tecnológicos, asegurando el cumplimiento de los objetivos y plazos establecidos.",
      "Gestionar y mantener actualizada la documentación técnica de los proyectos, facilitando la comunicación entre los equipos.",
      "Liderar y guiar al equipo de desarrollo, promoviendo buenas prácticas de programación y metodologías ágiles.",
      "Implementar metodologías ágiles como Scrum para optimizar los flujos de trabajo y la toma de decisiones en entornos híbridos.",
      "Desarrollar y mantener funcionalidades tanto en el backend como en el frontend utilizando PHP, Composer y PHPMyAdmin.",
      "Administrar bases de datos MySQL, optimizando consultas y garantizando la integridad de los datos.",
      "Desarrollar soluciones en HTML, CSS y JavaScript para mejorar la experiencia del usuario.",
      "Crear unidades de prueba y realizar depuración de código para garantizar la estabilidad del sistema.",
      "Participar en la estrategia de ventas y marketing técnico, simulando escenarios de negocio reales.",
    ],
  },
  {
    titulo: "Documentador de Software",
    empresa: "Start-Up TI Simulada",
    institucion: "Escuela Técnica N°29 D.E.06 'Reconquista de Buenos Aires'",
    tipoContrato: "Contrato de formación",
    periodo: "marzo 2021",
    ubicacion: "Provincia de Buenos Aires, Argentina (Híbrido)",
    descripcion: "En mi rol de Documentador de Software, fui responsable de redactar documentación técnica clara y estructurada para describir el funcionamiento del software. Mantuve actualizada la documentación para reflejar nuevas funcionalidades y cambios en el sistema. Trabajé en conjunto con desarrolladores y equipos de QA para comprender el software y garantizar la precisión de la documentación. Elaboré manuales de usuario y guías de instalación para facilitar el uso de las herramientas desarrolladas. También organicé la documentación de manera accesible y comprensible, revisando y editando los textos para garantizar coherencia, precisión y claridad. Además, brindé soporte a los usuarios y miembros del equipo en cuestiones relacionadas con la documentación técnica.",
    responsabilidades: [
      "Redactar documentación técnica clara y estructurada para describir el funcionamiento del software.",
      "Actualizar y mantener la documentación para reflejar nuevas funcionalidades y cambios en el software.",
      "Colaborar con desarrolladores y equipos de QA para comprender el software y garantizar la precisión de la documentación.",
      "Elaborar manuales de usuario y guías de instalación para facilitar el uso del software.",
      "Organizar la documentación de forma accesible y comprensible para diferentes públicos.",
      "Revisar y editar la documentación para garantizar coherencia, precisión y claridad.",
      "Brindar soporte a los usuarios y miembros del equipo en cuestiones relacionadas con la documentación técnica.",
    ],
  },
];
